### ISSUE TITLE
What does the plugin actually test?

### ISSUE THREAD

**Issue by danyj** [godaddy/wp-p3-profiler#1]
We are working with Unsyon theme framework and have performed few test
with your plugin and it always shows that Unyson  usage/performance is way to high
https://github.com/ThemeFuse/Unyson/issues/1581

Can you please advise what is being tested here so that we understand the chart better. 
Thank you!

**Comment by frankiejarrett** [comment]
Hi @danyj, thanks for the comment. Just curious if you've looked at the detailed breakdown or not?

At a high level, the plugin simply uses AJAX to load pages on the front of the site and uses the [PHP declare control structure](http://php.net/manual/en/control-structures.declare.php) and does a "tick" with every user function call made during a page load. This gives it the ability to determine what plugin files are executing which functions, and how long each call takes. It does this several times and then calculates averages to ignore anomalies.

Just a little more background about the P3 plugin: it was developed a while back by a developer that has since moved to another department here at GoDaddy. My team and I put the plugin here on GitHub in order to receive community feedback since perviously there was no meaningful way for developers to contact us and submit pull requests for bugs they were finding. My team and I do have plans to start revamping the plugin this year. All this to say, please do let us know any strange behavior you come across as this will help us a great deal.

**Comment by danyj** [comment]
@fjarrett  thnx for the reply. To be honest we are just bit concerned when we see Unyson numbers on your chart thus we are trying to figure out if these concerns are valid and if we should try to optimize the plugin for better performance.
